language: python
sudo: false
python:
 - "2.7"
 - "3.5"
 - "3.6"
 - "3.7"
env:
 - DJANGO_VERSION=1.11
 - DJANGO_VERSION=2.0
 - DJANGO_VERSION=2.1
matrix:
  exclude:
    - env: DJANGO_VERSION=2.0
      python: "2.7"
    - env: DJANGO_VERSION=2.1
      python: "2.7"
install:
 - pip install -q "Django>=${DJANGO_VERSION},<${DJANGO_VERSION}.99" "flake8"
script:
 - ./run.sh test
 - ./run.sh check
